### ISSUE TITLE
Annotation shape edits aren't preserved

### ISSUE THREAD

**Issue by hannahker** [mlexchange/mlex_highres_segmentation#114]
If I edit the shape of an annotation then trigger a callback that results in a redraw of that shape, the annotation snaps back to its original shape. 

https://github.com/mlexchange/mlex_highres_segmentation/assets/25990216/ae992ea6-02e1-4ce7-8c8b-011aabfe3f61

**Comment by hannahker** [comment]
Good news is that this does fire a `relayoutData` callback with the updated svg path. For example: 

```
{'shapes[0].path': 'M1256.5938864628827,625.09461426492L1131.0625909752553,625.09461426492L1046.521106259098,643.0276564774382L774.9636098981082,596.9141193595342L890.247452692868,768.5589519650655L877.4381368267835,819.7962154294032L880.0000000000005,937.64192139738L900.4949053857356,1019.6215429403203L841.5720524017472,1339.854439592431'}
```

It might take some effort to map this on to the structure of how we store annotations and figure out which entry to edit.

**Comment by cleaaum** [comment]
Amazing! I will be looking at that today, thanks @hannahker

**Comment by cleaaum** [comment]
Okay so here is the approach I am thinking! this: `shapes[0].path` refers to the shape modified in the order it was drawn (resets to 0 for a new slice). So if you have 2 shapes on a slice you will either get `shapes[0].path` or `shapes[1].path`. I think it could make sense to add a field in the store that matches this number so we can go back and modify it when the shape is modified. However, I am just curious as to what will happen when a shape is deleted. I think it may make more sense to implement that first so we can observe that behavior and implement this solution accordingly.
