### ISSUE TITLE
Create pixel mask from annotations

### ISSUE THREAD

**Issue by hannahker** [mlexchange/mlex_highres_segmentation#14]
Convert the SVG annotations for each slice to a multi-dimensional array such that it can be exported from the application.

From other demo app: 

Link to the store mask function: https://github.com/mlexchange/mlex_dash_segmentation_demo/blob/d8ae049cfb3164043ce251602ad8c0d9f3e2cb52/dash-seg/src/napp.py#L280

Link to the train_segmentation function that converts svg paths to a numpy array: https://github.com/mlexchange/mlex_dash_segmentation_demo/blob/d8ae049cfb3164043ce251602ad8c0d9f3e2cb52/dash-seg/src/napp.py#L532

**Comment by danton267** [comment]
#### save images who have a hand drawn mask
    #### save the shape of those saved images for converting mask from path to array
    masks_data = {k:v for (k,v) in masks_data.items() if bool(v)}
    image_index_with_mask = list(masks_data.keys()) #slice index that is labeled
    if seg_dropdown_value == 'K-Means':
         if image_index_with_mask:
             for im_index in image_index_with_mask:
                 im = np_volume[int(im_index)]
                 imageio.imsave(IM_TRAINING_DIR / '{}_for_training.tif'.format(im_index), im)
         else:
             for index in range(len(np_volume)):
                 im = np_volume[index]
                 imageio.imsave(IM_TRAINING_DIR / '{}_for_training.tif'.format(index), im)

    else:
        im_shape_list = []
        if image_store_data:
            for im_index in image_index_with_mask:
                im_str = image_store_data[list(image_store_data.keys())[int(im_index)]][1]
                im_decode = base64.b64decode(im_str)
                im_bytes = io.BytesIO(im_decode)
                im = PIL.Image.open(im_bytes).convert('L')  # convert to grayscale

                im_shape = (im.height, im.width)
                imageio.imsave(IM_TRAINING_DIR / '{}_for_training.tif'.format(im_index), im)
                im_shape_list.append(im_shape)

        else:  # no uploaded data, so use default
            for im_index in image_index_with_mask:
                im = np_volume[int(im_index)]
                imageio.imsave(IM_TRAINING_DIR / '{}_for_training.tif'.format(im_index), im)
                im_shape_list.append(im.shape[0:2])

        #### Create masks from the svg shape data stored in the hidden div ####
        mask_file_names = mask_tasks.create_save_masks(masks_data, MASK_OUTPUT_DIR, im_shape_list)


Do we take all of that code, even though some of it is not implemented?

**Comment by hannahker** [comment]
Notes on full vs sparse array? For just the annotations, it is likely that we can just export a sparse array across slices - data isn't required where there is no labelling. Necessary information is about which slice number is labelled. This is also input into the ML model.
