### ISSUE TITLE
Better notification of dataset availability

### ISSUE THREAD

**Issue by dylanmcreynolds** [mlexchange/mlex_highres_segmentation#162]

**Comment by dylanmcreynolds** [comment]
Right now, when tiled knows about a dataset, the user has to refresh the segmentation app to know about it. The user can refresh the browser, but then they loose their current masks.

In the short term, we would like to add a data refresh button to the application, so that it asks tiled for its list of data sets so that the whole browser does not have to refresh.

In the long term, we should think about a notification process where the reconstruction code can notify everyone that a dataset is available. This is where a tool like kafka might be very useful.

**Comment by zhuowenzhao** [comment]
I have made data_utils functions into a class object and added a refresh button next to the dataset dropdown window. I have recreated a https://github.com/mlexchange/mlex_highres_segmentation/pull/166.
