### ISSUE TITLE
Integrate model statistics, DVC

### ISSUE THREAD

**Issue by dylanmcreynolds** [mlexchange/mlex_highres_segmentation#163]
We would like to investigate using DVC to store, manage and display model running statistics, linked into the segmentation app.

**Comment by xiaoyachong** [comment]
use dvc commands and the DVCLive package

**Comment by xiaoyachong** [comment]
A new class called Trainer() should be added to DLSIA: https://github.com/mlexchange/mlex_dlsia_segmentation_prototype/issues/7

Then we can integrate DVC without modifying the DLSIA function at our end.
