### ISSUE TITLE
Identify data output format required for compatibility with Napari

### ISSUE THREAD

**Issue by hannahker** [mlexchange/mlex_highres_segmentation#25]
Export of annotations from the app should be compatible with Napari. The scope of this ticket is to identify those requirements.

Documentation to reference:
- https://github.com/adamltyson/napari-tutorials/blob/master/tutorials/labels.md#labels-data
- https://napari.org/stable/

**Comment by tamidodo** [comment]
Napari can support numpy-like arrays, including [dask arrays](https://docs.dask.org/en/stable/array.html), an [xarrays](http://xarray.pydata.org/en/stable/generated/xarray.DataArray.html), and [zarr arrays](https://zarr.readthedocs.io/en/stable/api/core.html). They use a "labels layer" for annotations which is a class that requires values in the array to be integer valued, and the "background label" ie. no annotation must be 0.

**Comment by hannahker** [comment]
@tamidodo what do you think is the most suitable file format to support this? Some options in mind are Pickle, netCDF, Zarr?

**Comment by hannahker** [comment]
No strict requirements here, think about smallest file size that supports import to Napari.

**Comment by hannahker** [comment]
Closing now, with follow up in #28
