### ISSUE TITLE
Index annotations according to a given image slice 

### ISSUE THREAD

**Issue by hannahker** [mlexchange/mlex_highres_segmentation#29]
A given annotation should only correspond to the image slice where it was drawn. 

- [ ] Annotations should not persist when someone slices across images 
- [ ] When the user comes back to a given slice, they should see any annotations that they previously added for that slice, provided the "view annotation layer" is turned on

We have this logic in progress, but it feels buggy when I'm testing the app as I often get `KeyErrors` like this: 

```
Traceback (most recent call last):
  File "/Users/hannahker/Desktop/mlex/mlex_highres_segmentation/callbacks/control_bar.py", line 60, in annotation_visibility
    patched_figure["layout"]["shapes"] = store[image_idx]
KeyError: '1'
```

**Comment by danton267** [comment]
addressed in #32
