### ISSUE TITLE
Need to disable the left hand side controls while image is loading

### ISSUE THREAD

**Issue by tamidodo** [mlexchange/mlex_highres_segmentation#41]
Any buttons clicked (annotation class, annotation mode, etc.) before the loading spinner has disappeared and the image has loaded will not actually change the property it's meant to change. ie. if you click on circle drawing mode before the graph loads, when you start drawing it will still be on open freeform mode even though the circle button has the active state styling.

**Comment by danton267** [comment]
We have 3 options

1. create the left-hand controls after the user selects the project and figure finishes loading
2. leave it as-is but disable every control when the figure is loading and enable it after it finishes
3. add LoadingOverlay and
   1. fully hide controls (with white colour let's say)
   2. add a spinner on top of it to indicate they are not usable right now.

which approach do we take? @hannahker

**Comment by hannahker** [comment]
Let's go for #2.
