### ISSUE TITLE
Allow use to come back to their annotation session

### ISSUE THREAD

**Issue by hannahker** [mlexchange/mlex_highres_segmentation#55]
An app user should have the ability to save their in-progress annotations and annotation classes, allowing them to resume the same work after closing the application.

We can approach this in a couple ways: 

A. **(easier)** The application supports exporting and loading in data for a user's annotation session. This exporting is already developed, so we'd just need to add in the ability to load these files in to the app. The Dash app remains stateless with this approach. 

B. **(more convenient for user)** The application saves the data for a user's annotation session on an external resource. The user can access and reload a session fully through the UI. Two options for external resources were discussed: 
     - Using the SplashML tool (developed by LBL), which is built on top of MongoDB.
     - Using the same Tiled server where the rest of the app's data is stored.

**Comment by danton267** [comment]
We have this functionality coded in #11. Can extract relevant bits and add them to the current codebase.

**Comment by danton267** [comment]
What should be the user story with the "state" of the app when they log in?
Example:

1. user logs in and is presented with options
   - select project
   - import new project data
2. when user selects project they could be presented with
   - Start new annotation
   - Load existing annotation (to view or continue annotating) - they would be presented with all their saved states
   - Load ML annotation - they would be presented with all the times that model was run and created results
3. Load app

- Have "save annotations" options - whether locally or in a db
- always have "load" which brings up options mentioned in step 2. (load existing annotations to continue/load ml annotations)
