### ISSUE TITLE
MVP: Visualize results from ML job in app

### ISSUE THREAD

**Issue by hannahker** [mlexchange/mlex_highres_segmentation#62]
-  User should be able to visualize the segmented outputs once their job has been completed successfully.
  - [ ] Underneath each project dropdown there should be another dropdown which lets users select the classification results. Only show this dropdown if the project has a completed classification
- [ ] Segmented image should overlay the original image data 
  - [ ] Colours of segmented pixels should match the colour of the class that the user-defined when annotating (since we don't 
  - [ ] The user should be able to "hide" the class from the annotation by clicking the legendstore anything in the DB yet, no need to finish it but do create a placeholder that we can then simply replace with real colours)
- when the user is viewing classification results:
  - [ ] Add a button that lets the user show/hide all ML classification annotations (so that if the user wishes they can refine the annotations)

Blocker:
- We currently don't have a pipeline to put the segmented results on the Tiled server.

**Comment by danton267** [comment]
- should annotation tool controls be disabled or hidden?
- should (original) user annotations be hidden/not used when the user chooses to view ML annotations?
- should the user be able to "hide" the class from the annotation by clicking the legend?

**Comment by TibbersHao** [comment]
> * should annotation tool controls be disabled or hidden?
Not necessarily.

> * should (original) user annotations be hidden/not used when the user chooses to view ML annotations?
We should have a button to toggle user annotation on/off when visualizing the ML segmentation results. 

> * should the user be able to "hide" the class from the annotation by clicking the legend?
That would be a great feature to have.
