### ISSUE TITLE
Add support for full screen image viewing

### ISSUE THREAD

**Issue by hannahker** [mlexchange/mlex_highres_segmentation#63]
The user should be able to collapse the control sidebar to enter a full-screen image annotation mode. The top slider should still be visible and the user would be able to switch between annotation modes using hot keys.

**Comment by danton267** [comment]
scoping questions:
- close the left bar as a drawer component or open the image view as fullscreen
- add notifications when using key binds to indicate what was selected?
  - only do this when the left bar is closed?

**Comment by Wiebke** [comment]
We were imagining the image view as full screen and interaction through key binds. I believe a notification on changing interaction mode would be needed then or at least some indication that the mode has changed. 

A notification could also be helpful in the general case (with the bar open)

**Comment by danton267** [comment]
Things left to do in the PR:

- [ ] ensure that windows doesn't overflow on any screen
- [ ] ensure that the size of the image is correctly assigned on any screen size
