### ISSUE TITLE
Support for non square datasets

### ISSUE THREAD

**Issue by hannahker** [mlexchange/mlex_highres_segmentation#65]
The image viewer should support rectangular image datasets (ie. not just a square as is currently). Blocked by #64.

**Comment by danton267** [comment]
@MinaMirz figure size
- try different aspect ration / cutoffs see what looks good, maybe define it based on the img shape
- rectangular figure support (LBL will upload data soon)

possible things to implement:

- Have the image fit into the whole page
- add black bars to the side
- on the page load have the image fit vertically to begin with (after that when they zoom in and change slices, the zoom will be preserved)
