### ISSUE TITLE
Implement z-axis slider to view different images in the same dataset

### ISSUE THREAD

**Issue by hannahker** [mlexchange/mlex_highres_segmentation#7]
![Screen Shot 2023-06-19 at 5 29 05 PM](https://github.com/mlexchange/mlex_highres_segmentation/assets/25990216/4e137918-505d-4861-ba63-676785919d58)

See the (currently non-functional) slider at the bottom of the image here

**Comment by danton267** [comment]
PR #9

**Comment by hannahker** [comment]
Closed with #9
