### ISSUE TITLE
Update UI for annotations classes

### ISSUE THREAD

**Issue by hannahker** [mlexchange/mlex_highres_segmentation#94]
The overall UI for the annotations editor should be updated to match the [Figma mocks](https://www.figma.com/file/r2QEIBpRKbR6PQMFoocJVb/ML-Exchange-HighRes-Segmentation?type=design&node-id=0%3A1&mode=design&t=YE330ZuZKNd9rTTl-1). 

- Each Class should be in a small card like the "Class 1", "New feature", "Test" examples below. By default, only the "Class 1" option should exist. 
- The Toolbar should also be updated so that what is currently the "Pan and zoom" option, is separated on the left side and colored slightly differently and has the hand icon instead of the Power icon. We can also remove the "View" switch for now. 
- "Drawing toolbar" and "Manage classes" text should be right aligned and added to the layout
- When a user clicks on a class, it should be selected in light grey. The annotations should be drawn on the image with the correct color. 

![Image](https://github.com/mlexchange/mlex_highres_segmentation/assets/25990216/b19c84b8-fcd7-4fac-a9e8-96b5702a0b3a)

**Comment by Wiebke** [comment]
@cleaaum This may be already be fixed in the rework of this part: On the latest version on main 4ae10c8, when typing out class names, key binds get triggered, leading to some unwanted side effects.

**Comment by cleaaum** [comment]
@Wiebke yes this has been fixed and is addressed in #97 !
